### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by pju-** [mattstein/snipcart-craft-plugin#4]
Hello, it seems there is not authentication taking place with the "order completed" webhook. Is that right?
So anyone sending a faked post request can mess with the inventory if one would implement the hook as is?

**Comment by couellet** [comment]
Webhook requests can be validated this way: http://docs.snipcart.com/configuration/json-crawler#validating-the-request

I don't think it would be very hard to add to the plugin.

**Comment by mattstein** [comment]
Thanks @pju- and @couellet! I'll get the plugin updated when I can and close this out.

**Comment by mattstein** [comment]
All set with this update, which includes a bit more cleanup as well. Thanks again for reporting, @pju-, and @couellet for help understanding the validation process.
